import unittest
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_ROOT = PROJECT_ROOT / "web"
STYLES_CSS = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")


class StockScorePageTemplateTests(unittest.TestCase):
    def test_stock_score_page_uses_homepage_shell_structure(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('class="app-shell', html)
        self.assertIn('class="topbar', html)
        self.assertIn('LOCAL SCORE TERMINAL', html)
        self.assertIn('class="topbar-actions', html)
        self.assertNotIn('>Home</a>', html)
        self.assertIn('id="stock-score-topbar-tools"', html)
        self.assertIn('id="stock-score-topbar-actions"', html)
        self.assertEqual(4, html.count('stock-score-topbar-action'))
        self.assertIn('>RPS</a>', html)
        self.assertIn('>财务评分</a>', html)
        self.assertIn('>相对估值</a>', html)
        self.assertIn('id="stock-score-data-update-btn"', html)
        self.assertLess(html.index('id="stock-score-data-update-btn"'), html.index('class="search-grid stock-score-lead-grid"'))
        self.assertLess(html.index('id="stock-score-data-update-info"'), html.index('class="search-grid stock-score-lead-grid"'))

    def test_index_page_redirects_to_stock_score_homepage(self) -> None:
        html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        self.assertIn('/stock-score.html', html)
        self.assertNotIn('Stock Window Volume', html)

    def test_stock_score_page_has_profile_summary_slots(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('id="score-profile-strip"', html)
        self.assertIn('id="score-workbench-totals"', html)
        self.assertIn('id="stock-score-query-totals"', html)
        self.assertIn('id="stock-score-basic-info-card"', html)
        self.assertIn('id="score-header" class="stock-score-summary visible"', html)
        self.assertIn('id="score-home-intro"', html)
        self.assertIn('class="stock-score-home-intro"', html)
        self.assertIn('id="score-home-intro-points"', html)
        self.assertIn('首页可先查看使用说明与当前数据口径', html)
        self.assertNotIn('id="score-methodology-note"', html)
        self.assertIn('class="industry-score-peer-trigger metric-value"', html)
        self.assertIn('id="hdr-total-industry" class="industry-score-peer-trigger metric-value"', html)
        self.assertIn('id="hdr-total-market-rank"', html)
        self.assertIn('id="hdr-total-industry-rank"', html)
        self.assertIn('id="hdr-total-industry-meta"', html)
        self.assertNotIn('申万二级行业内相对评分', html)
        self.assertNotIn('id="hdr-total-market" class="metric-value">—<span class="max">/100</span>', html)
        self.assertNotIn('id="hdr-total-industry" class="industry-score-peer-trigger">—<span class="max">/100</span>', html)
        self.assertIn('id="financial-detail-toggle"', html)
        self.assertNotIn('id="hdr-industry-display"', html)
        self.assertNotIn('<h3>基础画像</h3>', html)
        self.assertNotIn('id="hdr-industry-l1"', html)
        self.assertNotIn('id="hdr-industry-l2"', html)
        self.assertNotIn('id="hdr-core-concepts"', html)
        self.assertIn('id="hdr-rps-summary"', html)
        self.assertIn('id="hdr-valuation-summary"', html)
        self.assertIn('行业加权PE', html)
        self.assertIn('行业加权PS', html)
        self.assertIn('行业温度', html)
        self.assertIn('stock-score-temperature-trigger', html)
        self.assertIn('id="industry-temperature-history-dialog"', html)
        self.assertIn('id="industry-temperature-history-chart"', html)
        self.assertIn('id="industry-temperature-history-tbody"', html)
        self.assertNotIn('二级行业温度', html)
        valuation_section = html.split('id="hdr-valuation-summary"', 1)[1]
        self.assertIn('stock-score-valuation-temperature-field', valuation_section)
        self.assertLess(valuation_section.index('行业温度'), valuation_section.index('行业加权PE'))
        self.assertLess(valuation_section.index('行业温度'), valuation_section.index('行业加权PS'))
        self.assertIn('行业样本', html)
        self.assertIn('样本状态', html)
        self.assertIn('行业内估值位置', html)
        self.assertIn('区间标签', html)
        self.assertIn('class="stock-score-profile-cluster"', html)
        self.assertIn('查询股票后显示细分指标', html)
        self.assertIn('class="stock-score-empty-row"', html)
        self.assertIn('id="stock-score-search-concepts"', html)
        self.assertIn('id="stock-score-search-concepts-label"', html)
        self.assertIn('id="stock-score-search-concepts-value"', html)
        self.assertIn('id="stock-score-data-update-btn"', html)
        self.assertIn('id="stock-score-data-update-info"', html)
        self.assertIn('id="stock-score-data-update-retry-btn"', html)
        self.assertIn('重试失败项', html)
        self.assertIn('src="/stock-score.js?v=', html)
        self.assertIn('stock-score.js?v=20260505-update-progress', html)
        js = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('行业相对估值快照（含同业估值表）', js)
        self.assertIn('member_valuation_rows', js)
        self.assertIn('member_valuation_row_count', js)
        self.assertIn('complete_member_valuation_industry_count', js)
        self.assertIn('formatDataUpdateErrorMessage', js)
        self.assertIn('renderDataUpdateJobProgress', js)
        self.assertIn('/api/data-update-retry', js)
        self.assertIn('data_update_job', js)
        self.assertIn('当前进度', js)
        self.assertIn('数据更新已停止或失败', js)
        self.assertNotIn('全量更新失败: ${error.message}', js)
        self.assertIn('max-height', STYLES_CSS.split('.stock-score-data-update-info', 1)[1].split('}', 1)[0])
        self.assertIn('overflow', STYLES_CSS.split('.stock-score-data-update-info', 1)[1].split('}', 1)[0])
        self.assertNotIn('src="/stock-score.js"', html)
        self.assertNotIn('正在读取当前数据日期', html)
        self.assertNotIn('支持代码', html)
        self.assertNotIn('支持 market:symbol', html)
        self.assertNotIn('附带行业内对照', html)
        self.assertIn('class="status stock-score-status stock-score-search-status"', html)
        self.assertNotIn('id="quick-stock-list"', html)
        self.assertNotIn('id="recent-searches"', html)
        self.assertIn('id="hdr-basic-price"', html)
        self.assertIn('id="hdr-basic-change"', html)
        self.assertNotIn('id="hdr-basic-volume-ratio"', html)
        self.assertIn('id="hdr-basic-ps-ttm"', html)
        self.assertIn('id="hdr-basic-market-cap"', html)
        self.assertIn('id="hdr-basic-total-shares"', html)
        self.assertIn('id="hdr-basic-float-shares"', html)
        self.assertIn('id="hdr-basic-eps"', html)
        self.assertIn('id="hdr-basic-dynamic-pe"', html)
        basic_info_section = html.split('id="stock-score-basic-info-card"', 1)[1].split('</article>', 1)[0]
        self.assertIn('PE-TTM', basic_info_section)
        self.assertIn('待加载PE-TTM', basic_info_section)
        self.assertNotIn('PE(动)', basic_info_section)
        self.assertNotIn('待加载动态PE', basic_info_section)
        self.assertLess(html.index('id="hdr-basic-dynamic-pe"'), html.index('id="hdr-basic-market-cap"'))
        self.assertLess(html.index('id="hdr-basic-eps"'), html.index('id="hdr-basic-total-shares"'))
        self.assertIn('id="stock-score-basic-info-card"', html)
        self.assertLess(html.index('id="stock-score-query-totals"'), html.index('id="stock-score-basic-info-card"'))
        self.assertLess(html.index('id="stock-score-basic-info-card"'), html.index('id="score-header"'))
        self.assertIn('id="ai-financial-report"', html)
        self.assertIn('id="ai-report-btn"', html)
        self.assertIn('id="ai-report-copy-btn"', html)
        self.assertIn('id="ai-report-overall"', html)
        self.assertIn('id="ai-report-raw-data"', html)
        self.assertIn('id="ai-report-raw-table"', html)
        self.assertIn('id="ai-report-raw-toggle"', html)
        self.assertNotIn('id="latest-report-analysis"', html)
        self.assertNotIn('id="analysis-strengths"', html)
        self.assertNotIn('id="analysis-risks"', html)

    def test_stock_score_page_has_homepage_style_cards_for_score_sections(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('class="search-card', html)
        self.assertIn('class="profile-card', html)
        self.assertIn('class="metric-card', html)
        self.assertIn('.stock-score-home-intro', STYLES_CSS)
        self.assertIn('.stock-score-home-intro-points', STYLES_CSS)
        self.assertIn('.stock-score-home-intro-chip', STYLES_CSS)
        self.assertIn('.stock-score-empty-state', STYLES_CSS)
        self.assertIn('.stock-score-empty-row', STYLES_CSS)
        self.assertIn('.stock-score-valuation-temperature-field', STYLES_CSS)
        self.assertIn('.industry-temperature-history-chart', STYLES_CSS)
        self.assertIn('.industry-temperature-history-table-wrap', STYLES_CSS)

    def test_stock_score_page_has_dual_dimension_panels_and_rps_rank_analysis_modules(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('id="dim-cards-market"', html)
        self.assertIn('id="dim-cards-industry"', html)
        self.assertNotIn('QUICK PICKS', html)
        self.assertNotIn('快速股票', html)
        self.assertNotIn('行业总览', html)
        self.assertIn('id="hdr-rps20"', html)
        self.assertIn('id="hdr-rps50"', html)
        self.assertIn('id="hdr-rps120"', html)
        self.assertIn('id="hdr-rps250"', html)
        self.assertNotIn('id="hdr-rank-summary"', html)
        self.assertNotIn('id="hdr-rank-market"', html)
        self.assertNotIn('id="hdr-rank-industry"', html)
        self.assertIn('id="hdr-industry-rps-summary"', html)
        self.assertIn('id="hdr-industry-rps20"', html)
        self.assertIn('id="hdr-industry-rps50"', html)
        self.assertIn('id="hdr-industry-rps120"', html)
        self.assertIn('id="hdr-industry-rps250"', html)
        self.assertIn('>个股RPS<', html)
        self.assertIn('>二级行业RPS<', html)
        self.assertIn('待加载RPS20', html)
        self.assertIn('待加载RPS50', html)
        self.assertIn('待加载RPS120', html)
        self.assertIn('待加载RPS250', html)
        self.assertNotIn('待加载行业RPS20', html)
        self.assertNotIn('待加载行业RPS50', html)
        self.assertNotIn('待加载行业RPS120', html)
        self.assertNotIn('待加载行业RPS250', html)
        self.assertIn('id="hdr-valuation-industry-pe"', html)
        self.assertIn('id="hdr-valuation-industry-ps"', html)
        self.assertIn('id="hdr-valuation-temperature"', html)
        self.assertIn('id="hdr-valuation-classification"', html)
        self.assertIn('id="hdr-valuation-classification-desc"', html)
        self.assertIn('估值分类', html)
        self.assertIn('分类说明', html)
        self.assertIn('id="hdr-valuation-sample-count"', html)
        self.assertIn('id="hdr-valuation-sample-status"', html)
        self.assertIn('id="hdr-valuation-percentile"', html)
        self.assertIn('id="hdr-valuation-band"', html)
        self.assertIn('id="ai-financial-report"', html)
        self.assertIn('id="ai-report-btn"', html)
        self.assertIn('id="ai-report-copy-btn"', html)
        self.assertIn('id="ai-report-overall"', html)
        self.assertIn('id="ai-report-raw-data"', html)
        self.assertIn('id="ai-report-raw-table"', html)
        self.assertIn('<details id="ai-report-raw-data"', html)
        self.assertIn('class="ai-report-raw-group-head"', html)
        self.assertIn('class="ai-report-raw-head-main"', html)
        self.assertIn('class="ai-report-raw-head-sub"', html)
        self.assertIn('报告期', html)
        self.assertIn('营收(亿)', html)
        self.assertIn('营收同比', html)
        self.assertIn('净利润(亿)', html)
        self.assertIn('净利润同比', html)
        self.assertIn('扣非净利润(亿)', html)
        self.assertIn('扣非同比', html)
        self.assertNotIn('财报日期', html)
        self.assertNotIn('公告日期', html)
        self.assertNotIn('资产负债率', html)
        self.assertNotIn('营业收入</th>', html)
        self.assertNotIn('净利润</th>', html)
        self.assertIn('id="ai-report-highlights"', html)
        self.assertIn('id="ai-report-risks"', html)
        self.assertIn('id="ai-report-positive"', html)
        self.assertIn('id="ai-report-negative"', html)
        self.assertIn('当期', html)
        self.assertIn('上年同期', html)
        self.assertIn('行业均分', html)
        self.assertNotIn('同比%', html)
        self.assertIn('全市场分', html)
        self.assertIn('行业内分', html)
        self.assertNotIn('>全市场<', html)
        self.assertNotIn('>行业内<', html)
        self.assertNotIn('>原始值<', html)
        self.assertIn('class="sub-period-current"', html)
        self.assertIn('class="sub-period-previous"', html)
        self.assertIn('class="sub-period-industry-average"', html)
        self.assertIn('id="industry-peer-dialog"', html)
        self.assertIn('id="industry-peer-title"', html)
        self.assertIn('id="industry-peer-status"', html)
        self.assertIn('id="industry-peer-tbody"', html)
        self.assertIn('id="industry-score-peer-dialog"', html)
        self.assertIn('id="industry-score-peer-title"', html)
        self.assertIn('id="industry-score-peer-status"', html)
        self.assertIn('id="industry-score-peer-valuation-summary"', html)
        self.assertIn('id="industry-score-peer-valuation-pe"', html)
        self.assertIn('id="industry-score-peer-valuation-ps"', html)
        self.assertIn('id="industry-score-peer-tbody"', html)
        industry_total_dialog = html.split('id="industry-score-peer-dialog"', 1)[1]
        self.assertIn('股票名称', html)
        self.assertNotIn('股票代码</th>', industry_total_dialog)
        self.assertIn('当前价格', html)
        self.assertIn('财务数据', html)
        self.assertIn('指标值', html)
        self.assertIn('报告日期', html)
        self.assertIn('盈利能力', html)
        self.assertIn('成长能力', html)
        self.assertIn('运营效率', html)
        self.assertIn('现金流质量', html)
        self.assertIn('偿债能力', html)
        self.assertIn('资产质量', html)
        self.assertIn('PS-TTM', html)
        self.assertIn('PE(动)', html)
        self.assertIn('总分', html)
        self.assertIn('industry-score-peer-stock-trigger', html)
        self.assertIn('industry-score-peer-row-trigger', html)
        self.assertIn('industry-score-peer-stock-main', html)
        self.assertIn('industry-score-peer-stock-meta', html)
        self.assertNotIn('class="sub-period-yoy"', html)
        # Sortable columns
        self.assertIn('class="sortable"', html)
        self.assertIn('data-col="total_score"', html)
        self.assertIn('data-col="current_price"', html)
        self.assertIn('data-col="ps_ttm"', html)
        self.assertIn('data-col="pe_ttm"', html)
        self.assertIn('data-col="profitability"', html)
        self.assertIn('data-col="growth"', html)
        self.assertIn('data-col="operating"', html)
        self.assertIn('data-col="cashflow"', html)
        self.assertIn('data-col="solvency"', html)
        self.assertIn('data-col="asset_quality"', html)
        # Non-sortable columns
        self.assertIn('data-col="-1">股票名称</th>', html)
        self.assertIn('data-col="-1">报告日期</th>', html)
        self.assertIn('点击排序', html)
        self.assertIn('class="sort-indicator"', html)

    def test_stock_score_script_fetches_and_renders_profile_summary(self) -> None:
        script = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('/api/stock-profile?symbol=', script)
        self.assertIn('/api/relative-valuation?market=', script)
        self.assertIn('/api/stock-score-report-history?', script)
        self.assertIn('fetchRelativeValuation', script)
        self.assertIn('renderRelativeValuationSummary', script)
        self.assertIn('resetScoreHeaderSummary', script)
        self.assertIn('setScoreHeaderIntroVisible(true);\n    resetStockScoreDashboardState();', script)
        self.assertIn('financial-detail-toggle', script)
        self.assertIn('hdr-industry-rps20', script)
        self.assertIn('hdr-industry-rps50', script)
        self.assertIn('hdr-industry-rps120', script)
        self.assertIn('hdr-industry-rps250', script)
        self.assertIn('industry_rps_20', script)
        self.assertIn('industry_rps_50', script)
        self.assertIn('industry_rps_120', script)
        self.assertIn('industry_rps_250', script)
        self.assertNotIn('hdr-industry-display', script)
        self.assertNotIn('hdr-industry-l1', script)
        self.assertNotIn('hdr-industry-l2', script)
        self.assertNotIn('hdr-core-concepts', script)
        self.assertIn('stock-score-search-concepts-value', script)
        self.assertIn('renderSearchConceptSummary', script)
        self.assertIn('MAX_RECENT_STOCK_SEARCHES', script)
        self.assertIn('/api/data-update-status', script)
        self.assertIn('/api/data-update-run', script)
        self.assertIn('fetchDataUpdateStatus', script)
        self.assertIn('fetchDataUpdateRun', script)
        self.assertIn('refreshDataUpdateStatus', script)
        self.assertIn('renderDataUpdateStatus', script)
        self.assertIn('stock-score-data-update-btn', script)
        self.assertIn('stock-score-data-update-info', script)
        self.assertIn("method: 'POST'", script)
        self.assertIn('正在启动全量数据更新...', script)
        self.assertIn('当前进度', script)
        self.assertIn('fetchDataUpdateRetry', script)
        self.assertIn('最新更新', script)
        self.assertNotIn('更新时间', script)
        self.assertIn("join('\\n')", script)
        self.assertIn('loadRecentStockSearches', script)
        self.assertIn('saveRecentStockSearch', script)
        self.assertIn('renderRecentStockSearches', script)
        self.assertIn('localStorage', script)
        self.assertIn('recent-search', script)
        self.assertIn('hdr-rps-summary', script)
        self.assertIn('hdr-industry-rps-summary', script)
        self.assertIn('RPS20: 暂无', script)
        self.assertIn('RPS50: 暂无', script)
        self.assertIn('RPS120: 暂无', script)
        self.assertIn('RPS250: 暂无', script)
        self.assertNotIn('二级行业RPS20: 暂无', script)
        self.assertIn('hdr-basic-price', script)
        self.assertIn('hdr-basic-change', script)
        self.assertNotIn('hdr-basic-volume-ratio', script)
        self.assertIn('hdr-basic-ps-ttm', script)
        self.assertIn('hdr-basic-market-cap', script)
        self.assertIn('hdr-basic-total-shares', script)
        self.assertIn('hdr-basic-float-shares', script)
        self.assertIn('hdr-basic-eps', script)
        self.assertIn('hdr-basic-dynamic-pe', script)
        self.assertIn('formatRelativeValuationNumber(payload?.pe_ttm)', script)
        self.assertIn('renderBasicInfoSummary', script)
        self.assertIn('renderIndustryTotalMeta', script)
        self.assertIn('renderRelativeValuationSummary', script)
        self.assertIn('hdr-valuation-industry-pe', script)
        self.assertIn('hdr-valuation-industry-ps', script)
        self.assertIn('hdr-valuation-temperature', script)
        self.assertIn('hdr-valuation-sample-count', script)
        self.assertIn('hdr-valuation-sample-status', script)
        self.assertIn('hdr-valuation-percentile', script)
        self.assertIn('hdr-valuation-band', script)
        self.assertNotIn('score-methodology-note', script)
        self.assertNotIn('renderScoreMethodology', script)
        self.assertIn('hdr-total-industry-meta', script)
        self.assertIn('hdr-total-market-rank', script)
        self.assertIn('hdr-total-industry-rank', script)
        self.assertIn('renderTotalScoreRankMeta', script)
        self.assertIn('basic_info', script)
        self.assertIn('basic-change-positive', script)
        self.assertIn('basic-change-negative', script)
        self.assertIn('basic-change-flat', script)
        self.assertNotIn('renderQuickStocks', script)
        self.assertIn('/api/stock-score-ai-report', script)
        self.assertIn('renderAiFinancialReport', script)
        self.assertIn('renderAiReportRawTable', script)
        self.assertIn('formatAmountYi', script)
        self.assertIn('yoyClassName', script)
        self.assertIn('formatPeriodBadge', script)
        self.assertIn('ai-report-period-badge', script)
        self.assertIn('ai-report-period-badge-q1', script)
        self.assertIn('ai-report-period-badge-q2', script)
        self.assertIn('ai-report-period-badge-q3', script)
        self.assertIn('ai-report-period-badge-q4', script)
        self.assertIn('ai-report-period-year', script)
        self.assertIn('ai-report-period-label', script)
        self.assertIn('ai-report-raw-cell', script)
        self.assertIn('ai-report-raw-metric', script)
        self.assertIn('ai-report-raw-trend', script)
        self.assertIn('ex_net_profit', script)
        self.assertIn('key === "free_cf"', script)
        self.assertIn('sub-period-current', script)
        self.assertIn('sub-period-previous', script)
        self.assertIn('sub-period-industry-average', script)
        self.assertNotIn('sub-period-yoy', script)
        self.assertIn('industry_raw_sub_indicator_avgs', script)
        self.assertIn('/api/stock-score-industry-peers', script)
        self.assertIn('/api/stock-score-industry-total-peers', script)
        self.assertIn('fetchIndustryPeerBenchmark', script)
        self.assertIn('fetchIndustryTotalPeerBenchmark', script)
        self.assertIn('openIndustryPeerDialog', script)
        self.assertIn('closeIndustryPeerDialog', script)
        self.assertIn('renderIndustryPeerDialog', script)
        self.assertIn('openIndustryScorePeerDialog', script)
        self.assertIn('closeIndustryScorePeerDialog', script)
        self.assertIn('renderIndustryScorePeerDialog', script)
        self.assertIn('industry-score-peer-valuation-pe', script)
        self.assertIn('industry-score-peer-valuation-ps', script)
        self.assertIn('industry_weighted_pe_ttm', script)
        self.assertIn('industry_weighted_ps_ttm', script)
        self.assertIn('ps_ttm', script)
        self.assertIn('pe_ttm', script)
        self.assertIn('industry-score-peer-stock-trigger', script)
        self.assertIn('industry-score-peer-row-trigger', script)
        self.assertIn('industry-score-peer-stock-main', script)
        self.assertIn('industry-score-peer-stock-meta', script)
        self.assertIn('tabindex="0"', script)
        self.assertIn('closest(".industry-score-peer-row-trigger")', script)
        self.assertIn('data-peer-market', script)
        self.assertIn('data-peer-symbol', script)
        self.assertIn('data-peer-stock-name', script)
        self.assertIn('industry-peer-trigger', script)
        self.assertIn('industry-score-peer-trigger', script)
        self.assertIn('industry-peer-row-current', script)
        self.assertIn('industry-score-peer-row-current', script)
        self.assertIn('formatTotalScore', script)
        self.assertNotIn('/100</span>', script)
        self.assertIn('currentValueTrendClass', script)
        self.assertIn('value-trend-positive', script)
        self.assertIn('value-trend-negative', script)
        self.assertIn('value-trend-flat', script)
        self.assertIn('formula:', script)
        self.assertIn('meaning:', script)
        self.assertIn('directionText', script)
        self.assertIn('越大越好', script)
        self.assertIn('越小越好', script)
        self.assertIn('扣除非经常性损益后的净利润 / 归属于母公司股东权益', script)
        self.assertIn('归属于母公司所有者的净利润 / 营业收入', script)
        self.assertIn('经营活动产生的现金流量净额 - 资本支出', script)
        self.assertIn('反映股东资本的核心回报效率', script)
        self.assertIn('反映每单位营收最终沉淀多少利润', script)
        self.assertIn('反映资本开支后的现金沉淀能力', script)
        self.assertIn('renderSubIndicatorDiagnostic', script)
        self.assertIn('sub_indicator_diagnostics', script)
        self.assertIn('scoreResult.sub_indicator_diagnostics', script)
        self.assertIn('evidence_strength', script)
        self.assertIn('needs_text_validation', script)
        self.assertIn('industry_scope', script)
        self.assertIn('validation_sources', script)
        self.assertIn('证据强度', script)
        self.assertIn('需文本验证', script)
        self.assertIn('行业适用', script)
        self.assertIn('建议验证来源', script)
        self.assertIn('stock-score-subdiag', script)
        self.assertIn('stock-score-subdiag-attribution', script)
        self.assertIn('stock-score-subdiag-impact', script)
        self.assertIn('stock-score-subdiag-explanation', script)
        self.assertIn('生成解释', script)
        self.assertIn('重新生成解释', script)
        self.assertIn('/api/stock-score-subdiag-explanation', script)
        self.assertIn('fetchSubdiagExplanation', script)
        self.assertIn('function currentStockIdentity()', script)
        self.assertIn('function isCurrentStockIdentity(identity)', script)
        self.assertIn('const stockIdentity = currentStockIdentity();', script)
        self.assertIn('if (!isCurrentStockIdentity(stockIdentity)) return;', script)
        self.assertIn('AI 正在生成该指标的业务解释', script)
        self.assertIn('点击按钮生成解释，默认不自动调用 AI。', script)
        self.assertIn('subdiag-explanation-status-', script)
        self.assertIn('subdiag-explanation-retry', script)
        self.assertIn('结论:', script)
        self.assertIn('原因:', script)
        self.assertIn('验证:', script)
        self.assertIn('置信:', script)
        self.assertIn('shortenTerminalLine', script)
        self.assertIn('subdiag-explanation-terminal-panel', script)
        self.assertIn('subdiag-explanation-status-chip', script)
        self.assertIn('subdiag-explanation-signal-grid', script)
        self.assertIn('subdiag-explanation-signal-chip', script)
        self.assertIn('toggleAiReportRawData', script)
        self.assertIn('ai-report-btn', script)
        self.assertIn('ai-report-copy-btn', script)
        self.assertIn('ai-report-raw-toggle', script)
        self.assertIn('navigator.clipboard', script)
        self.assertIn('payload.reports', script)
        self.assertIn('latest_report', script)
        self.assertIn('latest_period_label', script)
        self.assertIn('renderAiReportRawTable(reportHistory.reports || [])', script)
        self.assertIn('toggleAiReportRawData(Array.isArray(reportHistory.reports)', script)
        self.assertIn('已复制AI财报摘要', script)
        self.assertIn('sortIndustryScorePeerTable', script)
        self.assertIn('_industryScorePeerRows', script)
        self.assertIn('_renderIndustryScorePeerBody', script)
        self.assertIn('document.querySelectorAll("#industry-score-peer-dialog .sub-table th.sortable")', script)
        self.assertIn('点击列头可排序', script)

    def test_stock_score_script_resets_all_dashboard_regions_on_invalid_or_failed_query(self) -> None:
        script = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('function resetStockScoreDashboardState()', script)
        for expected_call in [
            'resetScoreHeaderSummary();',
            'resetProfileSummary();',
            'clearRadarCharts();',
            'clearDimCards();',
            'clearSubIndicatorTable();',
            'resetPeerDialogs();',
            'resetAiFinancialReport("查询股票后可生成分析");',
        ]:
            self.assertIn(expected_call, script)
        invalid_branch = script.split('if (!market || !symbol) {', 1)[1].split('return;', 1)[0]
        self.assertIn('resetStockScoreDashboardState();', invalid_branch)
        failed_score_branch = script.split('if (!ok || !total_score) {', 1)[1].split('return;', 1)[0]
        self.assertIn('resetStockScoreDashboardState();', failed_score_branch)
        fetch_error_branch = script.split('} catch (err) {', 1)[1].split('}', 1)[0]
        self.assertIn('resetStockScoreDashboardState();', fetch_error_branch)
        no_score_guard = 'renderScore(result);\n    if (!result?.ok || !result?.total_score) {'
        self.assertIn(no_score_guard, script)
        self.assertLess(script.index(no_score_guard), script.index('renderProfileSummary(profile);'))

    def test_stock_score_script_keeps_valuation_percentile_dialog_metric_aligned_with_summary(self) -> None:
        script = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('payload?.primary_metric || payload?.primary_percentile_metric', script)
        self.assertIn('payload?.primary_percentile', script)
        self.assertIn('估值不可比', script)
        self.assertIn('sortNullableNumericLast', script)
        self.assertIn('nullableNumberForSort', script)
        self.assertNotIn('Number(a._percentile_rank ?? "")', script)
        self.assertIn('正在加载行业估值同业样本...', script)
        self.assertIn('document.getElementById("industry-valuation-percentile-title").textContent = "行业估值位置对照";', script)
        self.assertIn('document.getElementById("industry-valuation-percentile-status").textContent = "正在加载行业估值同业样本...";', script)

    def test_stock_score_script_renders_dual_dimensions_rps_and_ai_financial_report(self) -> None:
        script = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('dim-cards-market', script)
        self.assertIn('STOCK_SCORE_EMPTY_STATES', script)
        self.assertIn('renderDimEmptyState', script)
        self.assertIn('renderSubIndicatorEmptyState', script)
        self.assertIn('查询股票后显示六维评分', script)
        self.assertIn('clearDimCards();', script)
        self.assertIn('clearSubIndicatorTable();', script)
        self.assertIn('查询股票后显示细分指标', script)
        self.assertIn('点击“生成AI财报解读”后显示结构化结论', script)
        self.assertIn('dim-cards-industry', script)
        self.assertIn('hdr-rps20', script)
        self.assertIn('hdr-rps50', script)
        self.assertIn('hdr-rps120', script)
        self.assertIn('hdr-rps250', script)
        self.assertIn('hdr-industry-rps-summary', script)
        self.assertIn('hdr-industry-rps20', script)
        self.assertIn('hdr-industry-rps50', script)
        self.assertIn('hdr-industry-rps120', script)
        self.assertIn('hdr-industry-rps250', script)
        self.assertIn('industry_rps_20', script)
        self.assertIn('industry_rps_50', script)
        self.assertIn('industry_rps_120', script)
        self.assertIn('industry_rps_250', script)
        self.assertNotIn('二级行业RPS20:', script)
        self.assertNotIn('二级行业RPS50:', script)
        self.assertNotIn('二级行业RPS120:', script)
        self.assertNotIn('二级行业RPS250:', script)
        self.assertNotIn('hdr-rank-market', script)
        self.assertNotIn('hdr-rank-industry', script)
        self.assertIn('hdr-valuation-industry-pe', script)
        self.assertIn('hdr-valuation-industry-ps', script)
        self.assertIn('hdr-valuation-temperature', script)
        self.assertIn('hdr-valuation-classification', script)
        self.assertIn('hdr-valuation-classification-desc', script)
        self.assertIn('formatRelativeValuationClassification', script)
        self.assertIn('industry_temperature_history', script)
        self.assertIn('renderIndustryTemperatureHistoryDialog', script)
        self.assertIn('drawIndustryTemperatureHistoryChart', script)
        self.assertIn('openIndustryTemperatureHistoryDialog', script)
        self.assertIn('行业历史估值温度', script)
        self.assertIn('加权PE-TTM', script)
        self.assertIn('A类 正常盈利', script)
        self.assertIn('按 PE-TTM 排位', script)
        self.assertIn('B类 微盈利畸高', script)
        self.assertIn('按 PS-TTM 排位', script)
        self.assertIn('C类 亏损经营', script)
        self.assertIn('仅在亏损同类中按 PS-TTM 辅助比较', script)
        self.assertIn('D类 高风险例外', script)
        self.assertIn('不输出常规估值分位', script)
        self.assertNotIn('盈利为正且PE-TTM有效，当前按 PE-TTM 在正常盈利同业中排位。', script)
        self.assertNotIn('盈利为正但PE失真，改按 PS-TTM 做行业内辅助排位。', script)
        self.assertNotIn('当前仍处亏损，仅在亏损经营同类中按 PS-TTM 辅助比较。', script)
        self.assertNotIn('无有效营收概念或净资产风险较高，原则上不输出常规估值分位。', script)
        self.assertIn('primary_percentile', script)
        self.assertIn('valuation_band_label', script)
        self.assertIn('industry_weighted_pe_ttm', script)
        self.assertIn('industry_weighted_ps_ttm', script)
        self.assertIn('ai-report-overall', script)
        self.assertIn('ai-report-highlights', script)
        self.assertIn('ai-report-risks', script)
        self.assertIn('ai-report-positive', script)
        self.assertIn('ai-report-negative', script)
        self.assertNotIn('latest_report_analysis', script)
        self.assertNotIn('analysis-strengths', script)
        self.assertNotIn('analysis-risks', script)

    def test_stock_score_dimension_panels_use_two_column_desktop_layout(self) -> None:
        self.assertIn('.stock-score-dim-panels {', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(2, minmax(0, 1fr));', STYLES_CSS)

    def test_industry_score_peer_dialog_is_scrollable_and_has_valuation_summary_styles(self) -> None:
        self.assertIn('.industry-score-peer-dialog {', STYLES_CSS)
        self.assertIn('overflow: auto;', STYLES_CSS)
        self.assertIn('.industry-score-peer-dialog-card {', STYLES_CSS)
        self.assertIn('grid-template-rows:', STYLES_CSS)
        self.assertIn('.industry-score-peer-table-wrap {', STYLES_CSS)
        self.assertIn('min-height: 0;', STYLES_CSS)
        self.assertIn('.industry-score-peer-valuation-summary {', STYLES_CSS)
        self.assertIn('.industry-score-peer-stock-trigger {', STYLES_CSS)
        self.assertIn('.industry-score-peer-row-trigger {', STYLES_CSS)
        self.assertIn('.industry-score-peer-stock-main {', STYLES_CSS)
        self.assertIn('.industry-score-peer-stock-meta {', STYLES_CSS)

    def test_stock_score_lead_area_uses_compact_asymmetric_layout(self) -> None:
        self.assertIn('.stock-score-lead-grid {', STYLES_CSS)
        self.assertIn('grid-template-columns: minmax(300px, 0.84fr) minmax(0, 1.16fr);', STYLES_CSS)
        self.assertIn('.stock-score-search-card {', STYLES_CSS)
        self.assertIn('padding: 16px 18px 14px;', STYLES_CSS)
        self.assertIn('.stock-score-profile-card {', STYLES_CSS)
        self.assertIn('padding: 16px 18px 14px;', STYLES_CSS)
        self.assertIn('.stock-score-search-hints {', STYLES_CSS)
        self.assertIn('.stock-score-search-hint {', STYLES_CSS)
        self.assertIn('.stock-score-search-status {', STYLES_CSS)
        self.assertIn('margin-top: 10px;', STYLES_CSS)
        self.assertIn('min-height: 46px;', STYLES_CSS)
        self.assertIn('.stock-score-topbar-tools {', STYLES_CSS)
        self.assertIn('.stock-score-topbar-actions {', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(4, 5.5em);', STYLES_CSS)
        self.assertIn('.stock-score-topbar-action {', STYLES_CSS)
        self.assertIn('white-space: nowrap;', STYLES_CSS)
        self.assertIn('width: 100%;', STYLES_CSS)
        self.assertIn('#stock-score-topbar-actions {', STYLES_CSS)
        self.assertIn('display: flex;', STYLES_CSS)
        self.assertIn('flex-wrap: nowrap;', STYLES_CSS)
        self.assertIn('font-size: 13px;', STYLES_CSS)
        self.assertIn('.stock-score-data-update-info {', STYLES_CSS)
        self.assertIn('white-space: pre-line;', STYLES_CSS)

    def test_stock_score_snapshot_cards_are_tighter(self) -> None:
        self.assertIn('.stock-score-search-stack {', STYLES_CSS)
        self.assertIn('.stock-score-profile-grid {', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(2, minmax(0, 1fr));', STYLES_CSS)
        self.assertIn('.stock-score-profile-cluster {', STYLES_CSS)
        self.assertIn('.stock-score-profile-cluster-head {', STYLES_CSS)
        self.assertIn('.stock-score-metrics {', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(2, minmax(0, 1fr));', STYLES_CSS)
        self.assertIn('.stock-score-query-totals {', STYLES_CSS)
        self.assertIn('.stock-score-basic-info-card {', STYLES_CSS)
        self.assertIn('.stock-score-basic-grid {', STYLES_CSS)
        self.assertIn('gap: 6px;', STYLES_CSS)
        self.assertIn('.stock-score-basic-info-card .stock-score-profile-field {', STYLES_CSS)
        self.assertIn('min-height: 56px;', STYLES_CSS)
        self.assertIn('grid-template-columns: auto minmax(0, 1fr);', STYLES_CSS)
        self.assertIn('align-items: center;', STYLES_CSS)
        self.assertIn('.stock-score-basic-info-card .profile-label {', STYLES_CSS)
        self.assertIn('color: #6f8899;', STYLES_CSS)
        self.assertIn('font-size: 10px;', STYLES_CSS)
        self.assertIn('.stock-score-basic-info-card .profile-value {', STYLES_CSS)
        self.assertIn('font-size: 18px;', STYLES_CSS)
        self.assertIn('color: #8bd8ff;', STYLES_CSS)
        self.assertIn('text-align: right;', STYLES_CSS)
        self.assertIn('justify-self: end;', STYLES_CSS)
        self.assertIn('.basic-change-positive {', STYLES_CSS)
        self.assertIn('.basic-change-negative {', STYLES_CSS)
        self.assertIn('.basic-change-flat {', STYLES_CSS)
        self.assertIn('.stock-score-profile-field {', STYLES_CSS)
        self.assertIn('align-content: start;', STYLES_CSS)
        self.assertIn('.stock-score-profile-cluster {', STYLES_CSS)
        self.assertIn('align-content: start;', STYLES_CSS)
        self.assertIn('.stock-score-profile-card-inner {', STYLES_CSS)
        self.assertIn('.ai-financial-report-card {', STYLES_CSS)
        self.assertIn('.ai-report-action-row {', STYLES_CSS)
        self.assertIn('.ai-report-copy-btn {', STYLES_CSS)
        self.assertIn('.ai-report-raw-data {', STYLES_CSS)
        self.assertIn('.ai-report-raw-value {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-quarter {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-annual {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q1 {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q2 {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q3 {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q4 {', STYLES_CSS)
        self.assertIn('.ai-report-period-year {', STYLES_CSS)
        self.assertIn('.ai-report-period-label {', STYLES_CSS)
        self.assertIn('.ai-report-raw-cell {', STYLES_CSS)
        self.assertIn('.ai-report-raw-metric {', STYLES_CSS)
        self.assertIn('.ai-report-raw-trend {', STYLES_CSS)
        self.assertIn('.ai-report-raw-group-head {', STYLES_CSS)
        self.assertIn('.ai-report-raw-head-main {', STYLES_CSS)
        self.assertIn('.ai-report-raw-head-sub {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-grid {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-attribution {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-impact {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-explanation {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-trigger {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-terminal-line {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-terminal-label {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-terminal-panel {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-status-chip {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-signal-grid {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-signal-chip {', STYLES_CSS)
        self.assertIn('.ai-report-yoy-positive {', STYLES_CSS)
        self.assertIn('.ai-report-yoy-negative {', STYLES_CSS)
        self.assertIn('.ai-report-yoy-flat {', STYLES_CSS)
        self.assertIn('.ai-report-raw-table td:nth-child(2),', STYLES_CSS)
        self.assertIn('.sub-period-current {', STYLES_CSS)
        self.assertIn('.sub-period-previous {', STYLES_CSS)
        self.assertIn('.sub-period-industry-average-btn {', STYLES_CSS)
        self.assertIn('.industry-peer-dialog {', STYLES_CSS)
        self.assertIn('.industry-peer-dialog[hidden] {', STYLES_CSS)
        self.assertIn('display: none !important;', STYLES_CSS)
        self.assertIn('.industry-peer-dialog-card {', STYLES_CSS)
        self.assertIn('.industry-peer-table-wrap {', STYLES_CSS)
        self.assertIn('.industry-peer-financial-data {', STYLES_CSS)
        self.assertIn('.industry-peer-row-current {', STYLES_CSS)
        self.assertIn('.stock-score-total-trigger {', STYLES_CSS)
        self.assertIn('.industry-score-peer-trigger {', STYLES_CSS)
        self.assertIn('font-size: clamp(24px, 4vw, 38px);', STYLES_CSS)
        self.assertIn('color: #ffb36b;', STYLES_CSS)
        self.assertIn('.industry-score-peer-dialog {', STYLES_CSS)
        self.assertIn('.industry-score-peer-dialog[hidden] {', STYLES_CSS)
        self.assertIn('.industry-score-peer-dialog-card {', STYLES_CSS)
        self.assertIn('.industry-score-peer-table-wrap {', STYLES_CSS)
        self.assertIn('.industry-score-peer-row-current {', STYLES_CSS)
        self.assertIn('.value-trend-positive {', STYLES_CSS)
        self.assertIn('.value-trend-negative {', STYLES_CSS)
        self.assertIn('.value-trend-flat {', STYLES_CSS)
        self.assertIn('.sub-rank-formula,', STYLES_CSS)
        self.assertIn('.sub-rank-meaning,', STYLES_CSS)
        self.assertIn('.sub-rank-direction {', STYLES_CSS)

    def test_stock_score_dimension_panels_collapse_on_mobile(self) -> None:
        self.assertIn('.stock-score-dim-panels,', STYLES_CSS)
        self.assertIn('grid-template-columns: 1fr;', STYLES_CSS)


if __name__ == "__main__":
    unittest.main()
