import unittest
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_ROOT = PROJECT_ROOT / "web"


class RpsPageTemplateTests(unittest.TestCase):
    def test_homepage_links_to_rps_pool_page(self) -> None:
        html = (WEB_ROOT / "index.html").read_text(encoding="utf-8")
        self.assertIn('href="/rps-pool.html"', html)
        self.assertNotIn('href="/rps-ranking.html"', html)

    def test_rps_pool_page_keeps_pool_filter_table_and_chart_only(self) -> None:
        html = (WEB_ROOT / "rps-pool.html").read_text(encoding="utf-8")
        self.assertIn('id="pool-level1"', html)
        self.assertIn('id="pool-level2"', html)
        self.assertIn('id="pool-concept-input"', html)
        self.assertIn('id="pool-tbody"', html)
        self.assertIn('id="pool-chart-section"', html)
        self.assertIn('id="industry-rps-section"', html)
        self.assertIn('id="industry-rps-tbody"', html)
        self.assertIn('二级行业RPS', html)
        self.assertIn('成分股', html)
        self.assertIn('data-sort-key="industry_rps_20"', html)
        self.assertIn('data-sort-key="industry_rps_50"', html)
        self.assertIn('data-sort-key="industry_rps_120"', html)
        self.assertIn('data-sort-key="industry_rps_250"', html)
        self.assertIn('data-industry-level2', html)
        self.assertIn('data-sort-key="rps_20"', html)
        self.assertIn('data-sort-key="rps_50"', html)
        self.assertIn('data-sort-key="rps_120"', html)
        self.assertIn('data-sort-key="rps_250"', html)
        self.assertIn('data-sort-direction="desc"', html)
        self.assertIn('class="pool-sort-indicator"', html)
        self.assertIn('RPS120', html)
        self.assertIn('RPS250', html)
        self.assertIn('申万行业', html)
        self.assertNotIn('>操作<', html)
        self.assertNotIn('pool-kline-btn', html)
        self.assertNotIn('id="full-ranking-section"', html)
        self.assertNotIn('id="rps-ranking-form"', html)
        self.assertNotIn('id="rps-ranking-tbody"', html)
        self.assertNotIn('RANKING FEED', html)
        self.assertNotIn('全部股票 RPS 排名', html)

    def test_rps_pool_script_removes_full_ranking_logic_and_supports_pool_sort(self) -> None:
        script = (WEB_ROOT / "rps-pool.js").read_text(encoding="utf-8")
        self.assertIn('applyPoolFilter', script)
        self.assertIn('renderPoolTable', script)
        self.assertIn('renderIndustryRpsTable', script)
        self.assertIn('buildIndustryRpsRows', script)
        self.assertIn('industryRpsData', script)
        self.assertIn('industryRpsSortKey', script)
        self.assertIn('industryRpsSortDirection', script)
        self.assertIn('toggleIndustryRpsSort', script)
        self.assertIn('sortIndustryRpsData', script)
        self.assertIn('loadIndustryKline', script)
        self.assertIn('buildIndustryKlineBars', script)
        self.assertIn('computeIndustryRpsHistory', script)
        self.assertIn('/api/industry-heatmap', script)
        self.assertIn('daily_volume', script)
        self.assertNotIn('volume: Number(cell?.stock_count || 0)', script)
        self.assertIn('rps_20: rps20[i]', script)
        self.assertIn('rps_50: rps50[i]', script)
        self.assertIn('rps_120: rps120[i]', script)
        self.assertIn('rps_250: rps250[i]', script)
        self.assertIn('loadPoolKline', script)
        self.assertIn('poolSortKey', script)
        self.assertIn('poolSortDirection', script)
        self.assertIn('togglePoolSort', script)
        self.assertIn('sortPoolData', script)
        self.assertIn('renderPoolSortIndicators', script)
        self.assertIn('pool-sort-active', script)
        self.assertIn('pool-sort-asc', script)
        self.assertIn('pool-sort-desc', script)
        self.assertIn('formatPoolIndustry', script)
        self.assertIn('level2', script)
        self.assertIn('rps_120', script)
        self.assertIn('rps_250', script)
        self.assertIn("tr.addEventListener('click'", script)
        self.assertNotIn("params.append('limit', '500')", script)
        self.assertNotIn('pool-kline-btn', script)
        self.assertNotIn('loadFullRanking', script)
        self.assertNotIn('bindRankingEvents', script)
        self.assertNotIn('fullRankingData', script)
        self.assertNotIn('rps-ranking-tbody', script)
        self.assertNotIn('/api/rps-ranking', script)

    def test_kline_chart_script_supports_multiline_price_tooltip_and_four_rps_lines(self) -> None:
        script = (WEB_ROOT / "kline-chart.js").read_text(encoding="utf-8")
        self.assertIn('rps_120', script)
        self.assertIn('rps_250', script)
        self.assertIn("label: 'RPS120'", script)
        self.assertIn("label: 'RPS250'", script)
        self.assertIn('日期', script)
        self.assertIn('开盘价', script)
        self.assertIn('最高价', script)
        self.assertIn('最低价', script)
        self.assertIn('收盘价', script)
        self.assertIn('成交量', script)
        self.assertIn('RPS20', script)
        self.assertIn('RPS50', script)
        self.assertIn('RPS120', script)
        self.assertIn('RPS250', script)
        self.assertIn('个股RPS', script)
        self.assertIn('kc-rps-guide', script)
        self.assertIn("querySelectorAll('.kc-rps-guide')", script)
        self.assertIn('d.rpsTop + d.rpsH', script)
        self.assertIn("document.createElementNS(ns, 'tspan')", script)

    def test_kline_chart_script_keeps_right_y_axis_labels_fully_visible(self) -> None:
        script = (WEB_ROOT / "kline-chart.js").read_text(encoding="utf-8")
        self.assertIn('marginRight: 48', script)
        self.assertIn("t.setAttribute('text-anchor', 'end')", script)
        self.assertIn("t.setAttribute('x', d.w - 4)", script)

    def test_rps_pool_page_has_no_rps_profile(self) -> None:
        html = (WEB_ROOT / "rps-pool.html").read_text(encoding="utf-8")
        self.assertNotIn('id="rps-profile-title"', html)
        self.assertNotIn('id="rps-profile-card"', html)


if __name__ == "__main__":
    unittest.main()
