import unittest
from pathlib import Path


PROJECT_ROOT = Path(__file__).resolve().parent.parent
WEB_ROOT = PROJECT_ROOT / "web"
STYLES_CSS = (WEB_ROOT / "styles.css").read_text(encoding="utf-8")


class StockScorePageTemplateTests(unittest.TestCase):
    def test_stock_score_page_uses_homepage_shell_structure(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('class="app-shell', html)
        self.assertIn('class="topbar', html)
        self.assertIn('LOCAL SCORE TERMINAL', html)
        self.assertIn('class="topbar-actions', html)

    def test_stock_score_page_has_profile_summary_slots(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('id="score-profile-strip"', html)
        self.assertIn('id="score-workbench-totals"', html)
        self.assertIn('id="financial-detail-toggle"', html)
        self.assertNotIn('id="hdr-industry-display"', html)
        self.assertIn('id="hdr-industry-l1"', html)
        self.assertIn('id="hdr-industry-l2"', html)
        self.assertIn('id="hdr-core-concepts"', html)
        self.assertIn('id="hdr-rps-summary"', html)
        self.assertIn('class="stock-score-profile-cluster"', html)
        self.assertIn('class="stock-score-search-hints"', html)
        self.assertIn('class="stock-score-search-hint"', html)
        self.assertIn('class="status stock-score-status stock-score-search-status"', html)
        self.assertNotIn('id="quick-stock-list"', html)
        self.assertIn('id="recent-searches"', html)
        self.assertIn('id="ai-financial-report"', html)
        self.assertIn('id="ai-report-btn"', html)
        self.assertIn('id="ai-report-copy-btn"', html)
        self.assertIn('id="ai-report-overall"', html)
        self.assertIn('id="ai-report-raw-data"', html)
        self.assertIn('id="ai-report-raw-table"', html)
        self.assertIn('id="ai-report-raw-toggle"', html)
        self.assertNotIn('id="latest-report-analysis"', html)
        self.assertNotIn('id="analysis-strengths"', html)
        self.assertNotIn('id="analysis-risks"', html)

    def test_stock_score_page_has_methodology_note_slot(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('id="score-methodology-note"', html)

    def test_stock_score_page_has_homepage_style_cards_for_score_sections(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('class="search-card', html)
        self.assertIn('class="profile-card', html)
        self.assertIn('class="metric-card', html)

    def test_stock_score_page_has_dual_dimension_panels_and_rps_rank_analysis_modules(self) -> None:
        html = (WEB_ROOT / "stock-score.html").read_text(encoding="utf-8")
        self.assertIn('id="dim-cards-market"', html)
        self.assertIn('id="dim-cards-industry"', html)
        self.assertNotIn('QUICK PICKS', html)
        self.assertNotIn('快速股票', html)
        self.assertNotIn('行业总览', html)
        self.assertIn('申万一级', html)
        self.assertIn('申万二级', html)
        self.assertIn('id="hdr-rps20"', html)
        self.assertIn('id="hdr-rps50"', html)
        self.assertIn('id="hdr-rps120"', html)
        self.assertIn('id="hdr-rps250"', html)
        self.assertIn('id="hdr-rank-summary"', html)
        self.assertIn('id="hdr-rank-market"', html)
        self.assertIn('id="hdr-rank-industry"', html)
        self.assertIn('id="ai-financial-report"', html)
        self.assertIn('id="ai-report-btn"', html)
        self.assertIn('id="ai-report-copy-btn"', html)
        self.assertIn('id="ai-report-overall"', html)
        self.assertIn('id="ai-report-raw-data"', html)
        self.assertIn('id="ai-report-raw-table"', html)
        self.assertIn('<details id="ai-report-raw-data"', html)
        self.assertIn('class="ai-report-raw-group-head"', html)
        self.assertIn('class="ai-report-raw-head-main"', html)
        self.assertIn('class="ai-report-raw-head-sub"', html)
        self.assertIn('报告期', html)
        self.assertIn('营收(亿)', html)
        self.assertIn('营收同比', html)
        self.assertIn('净利润(亿)', html)
        self.assertIn('净利润同比', html)
        self.assertIn('扣非净利润(亿)', html)
        self.assertIn('扣非同比', html)
        self.assertNotIn('财报日期', html)
        self.assertNotIn('公告日期', html)
        self.assertNotIn('资产负债率', html)
        self.assertNotIn('营业收入</th>', html)
        self.assertNotIn('净利润</th>', html)
        self.assertIn('id="ai-report-highlights"', html)
        self.assertIn('id="ai-report-risks"', html)
        self.assertIn('id="ai-report-positive"', html)
        self.assertIn('id="ai-report-negative"', html)
        self.assertIn('当期', html)
        self.assertIn('上期', html)
        self.assertIn('全市场分', html)
        self.assertIn('行业内分', html)
        self.assertNotIn('>全市场<', html)
        self.assertNotIn('>行业内<', html)
        self.assertNotIn('>原始值<', html)
        self.assertIn('class="sub-period-current"', html)
        self.assertIn('class="sub-period-previous"', html)
        self.assertIn('class="sub-period-yoy"', html)

    def test_stock_score_script_fetches_and_renders_profile_summary(self) -> None:
        script = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('/api/stock-profile?symbol=', script)
        self.assertIn('/api/stock-score-report-history?', script)
        self.assertIn('fetchReportHistory', script)
        self.assertIn('financial-detail-toggle', script)
        self.assertNotIn('hdr-industry-display', script)
        self.assertIn('hdr-industry-l1', script)
        self.assertIn('hdr-industry-l2', script)
        self.assertIn('hdr-core-concepts', script)
        self.assertIn('hdr-rps-summary', script)
        self.assertIn('recent-searches', script)
        self.assertIn('localStorage', script)
        self.assertIn('renderRecentSearches', script)
        self.assertNotIn('renderQuickStocks', script)
        self.assertIn('/api/stock-score-ai-report', script)
        self.assertIn('renderAiFinancialReport', script)
        self.assertIn('renderAiReportRawTable', script)
        self.assertIn('formatAmountYi', script)
        self.assertIn('yoyClassName', script)
        self.assertIn('formatPeriodBadge', script)
        self.assertIn('ai-report-period-badge', script)
        self.assertIn('ai-report-period-badge-q1', script)
        self.assertIn('ai-report-period-badge-q2', script)
        self.assertIn('ai-report-period-badge-q3', script)
        self.assertIn('ai-report-period-badge-q4', script)
        self.assertIn('ai-report-period-year', script)
        self.assertIn('ai-report-period-label', script)
        self.assertIn('ai-report-raw-cell', script)
        self.assertIn('ai-report-raw-metric', script)
        self.assertIn('ai-report-raw-trend', script)
        self.assertIn('ex_net_profit', script)
        self.assertIn('key === "free_cf"', script)
        self.assertIn('sub-period-current', script)
        self.assertIn('sub-period-previous', script)
        self.assertIn('sub-period-yoy', script)
        self.assertIn('renderSubIndicatorDiagnostic', script)
        self.assertIn('sub_indicator_diagnostics', script)
        self.assertIn('scoreResult.sub_indicator_diagnostics', script)
        self.assertIn('evidence_strength', script)
        self.assertIn('needs_text_validation', script)
        self.assertIn('industry_scope', script)
        self.assertIn('validation_sources', script)
        self.assertIn('证据强度', script)
        self.assertIn('需文本验证', script)
        self.assertIn('行业适用', script)
        self.assertIn('建议验证来源', script)
        self.assertIn('stock-score-subdiag', script)
        self.assertIn('stock-score-subdiag-attribution', script)
        self.assertIn('stock-score-subdiag-impact', script)
        self.assertIn('stock-score-subdiag-explanation', script)
        self.assertIn('生成解释', script)
        self.assertIn('重新生成解释', script)
        self.assertIn('/api/stock-score-subdiag-explanation', script)
        self.assertIn('fetchSubdiagExplanation', script)
        self.assertIn('function currentStockIdentity()', script)
        self.assertIn('function isCurrentStockIdentity(identity)', script)
        self.assertIn('const stockIdentity = currentStockIdentity();', script)
        self.assertIn('if (!isCurrentStockIdentity(stockIdentity)) return;', script)
        self.assertIn('AI 正在生成该指标的业务解释', script)
        self.assertIn('点击按钮生成解释，默认不自动调用 AI。', script)
        self.assertIn('subdiag-explanation-status-', script)
        self.assertIn('subdiag-explanation-retry', script)
        self.assertIn('结论:', script)
        self.assertIn('原因:', script)
        self.assertIn('验证:', script)
        self.assertIn('置信:', script)
        self.assertIn('shortenTerminalLine', script)
        self.assertIn('subdiag-explanation-terminal-panel', script)
        self.assertIn('subdiag-explanation-status-chip', script)
        self.assertIn('subdiag-explanation-signal-grid', script)
        self.assertIn('subdiag-explanation-signal-chip', script)
        self.assertIn('toggleAiReportRawData', script)
        self.assertIn('ai-report-btn', script)
        self.assertIn('ai-report-copy-btn', script)
        self.assertIn('ai-report-raw-toggle', script)
        self.assertIn('navigator.clipboard', script)
        self.assertIn('payload.reports', script)
        self.assertIn('latest_report', script)
        self.assertIn('latest_period_label', script)
        self.assertIn('renderAiReportRawTable(reportHistory.reports || [])', script)
        self.assertIn('toggleAiReportRawData(Array.isArray(reportHistory.reports)', script)
        self.assertIn('已复制AI财报摘要', script)

    def test_stock_score_script_references_score_methodology_note(self) -> None:
        script = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('score-methodology-note', script)
        self.assertIn('score_methodology', script)

    def test_stock_score_script_renders_dual_dimensions_rps_and_ai_financial_report(self) -> None:
        script = (WEB_ROOT / "stock-score.js").read_text(encoding="utf-8")
        self.assertIn('dim-cards-market', script)
        self.assertIn('dim-cards-industry', script)
        self.assertIn('hdr-rps20', script)
        self.assertIn('hdr-rps50', script)
        self.assertIn('hdr-rps120', script)
        self.assertIn('hdr-rps250', script)
        self.assertIn('hdr-rank-market', script)
        self.assertIn('hdr-rank-industry', script)
        self.assertIn('market_total_rank', script)
        self.assertIn('industry_total_rank', script)
        self.assertIn('ai-report-overall', script)
        self.assertIn('ai-report-highlights', script)
        self.assertIn('ai-report-risks', script)
        self.assertIn('ai-report-positive', script)
        self.assertIn('ai-report-negative', script)
        self.assertNotIn('latest_report_analysis', script)
        self.assertNotIn('analysis-strengths', script)
        self.assertNotIn('analysis-risks', script)

    def test_stock_score_dimension_panels_use_two_column_desktop_layout(self) -> None:
        self.assertIn('.stock-score-dim-panels {', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(2, minmax(0, 1fr));', STYLES_CSS)

    def test_stock_score_lead_area_uses_compact_asymmetric_layout(self) -> None:
        self.assertIn('.stock-score-lead-grid {', STYLES_CSS)
        self.assertIn('grid-template-columns: minmax(300px, 0.84fr) minmax(0, 1.16fr);', STYLES_CSS)
        self.assertIn('.stock-score-search-card {', STYLES_CSS)
        self.assertIn('padding: 16px 18px 14px;', STYLES_CSS)
        self.assertIn('.stock-score-profile-card {', STYLES_CSS)
        self.assertIn('padding: 16px 18px 14px;', STYLES_CSS)
        self.assertIn('.stock-score-search-hints {', STYLES_CSS)
        self.assertIn('.stock-score-search-hint {', STYLES_CSS)
        self.assertIn('.stock-score-search-status {', STYLES_CSS)
        self.assertIn('margin-top: 10px;', STYLES_CSS)
        self.assertIn('min-height: 46px;', STYLES_CSS)

    def test_stock_score_snapshot_cards_are_tighter(self) -> None:
        self.assertIn('.stock-score-search-stack {', STYLES_CSS)
        self.assertIn('.stock-score-profile-grid {', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(2, minmax(0, 1fr));', STYLES_CSS)
        self.assertIn('.stock-score-profile-cluster {', STYLES_CSS)
        self.assertIn('.stock-score-profile-cluster-head {', STYLES_CSS)
        self.assertIn('.stock-score-metrics {', STYLES_CSS)
        self.assertIn('grid-template-columns: repeat(2, minmax(0, 1fr));', STYLES_CSS)
        self.assertIn('.stock-score-profile-field {', STYLES_CSS)
        self.assertIn('align-content: start;', STYLES_CSS)
        self.assertIn('.stock-score-profile-cluster {', STYLES_CSS)
        self.assertIn('align-content: start;', STYLES_CSS)
        self.assertIn('.stock-score-workbench-grid {', STYLES_CSS)
        self.assertIn('.stock-score-profile-card-inner {', STYLES_CSS)
        self.assertIn('.ai-financial-report-card {', STYLES_CSS)
        self.assertIn('.ai-report-action-row {', STYLES_CSS)
        self.assertIn('.ai-report-copy-btn {', STYLES_CSS)
        self.assertIn('.ai-report-raw-data {', STYLES_CSS)
        self.assertIn('.ai-report-raw-value {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-quarter {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-annual {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q1 {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q2 {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q3 {', STYLES_CSS)
        self.assertIn('.ai-report-period-badge-q4 {', STYLES_CSS)
        self.assertIn('.ai-report-period-year {', STYLES_CSS)
        self.assertIn('.ai-report-period-label {', STYLES_CSS)
        self.assertIn('.ai-report-raw-cell {', STYLES_CSS)
        self.assertIn('.ai-report-raw-metric {', STYLES_CSS)
        self.assertIn('.ai-report-raw-trend {', STYLES_CSS)
        self.assertIn('.ai-report-raw-group-head {', STYLES_CSS)
        self.assertIn('.ai-report-raw-head-main {', STYLES_CSS)
        self.assertIn('.ai-report-raw-head-sub {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-grid {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-attribution {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-impact {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-explanation {', STYLES_CSS)
        self.assertIn('.stock-score-subdiag-trigger {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-terminal-line {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-terminal-label {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-terminal-panel {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-status-chip {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-signal-grid {', STYLES_CSS)
        self.assertIn('.subdiag-explanation-signal-chip {', STYLES_CSS)
        self.assertIn('.ai-report-yoy-positive {', STYLES_CSS)
        self.assertIn('.ai-report-yoy-negative {', STYLES_CSS)
        self.assertIn('.ai-report-yoy-flat {', STYLES_CSS)
        self.assertIn('.ai-report-raw-table td:nth-child(2),', STYLES_CSS)
        self.assertIn('.sub-period-current {', STYLES_CSS)
        self.assertIn('.sub-period-previous {', STYLES_CSS)
        self.assertIn('.sub-period-yoy {', STYLES_CSS)

    def test_stock_score_dimension_panels_collapse_on_mobile(self) -> None:
        self.assertIn('.stock-score-dim-panels,', STYLES_CSS)
        self.assertIn('grid-template-columns: 1fr;', STYLES_CSS)


if __name__ == "__main__":
    unittest.main()
